Repository MTES-MCT/aides-territoires, pull requests merged in 2020-12, with the labels that each got.

#327 Minisites : meilleur gestion des stats renvoyées par Matomo
  src/aids/admin.py
  src/minisites/views.py
  src/stats/utils.py
Labels: bug

#311 Déploiement sur Scalingo
  Pipfile
  Pipfile.lock
  src/.buildpacks
  src/.env.scalingo.example
  src/.gitignore
  src/Aptfile
  src/Pipfile
  src/Pipfile.lock
  src/Procfile
  src/core/settings/scalingo.py
  src/core/urls.py
  src/core/wsgi_scalingo.py
  src/scripts/postdeploy.sh
Labels: amélioration technique

#295 Fonctionnalités porteurs d'aides : page + logos
  src/backers/admin.py
  src/backers/migrations/0007_auto_20201203_1303.py
  src/backers/migrations/0008_add_description_field.py
  src/backers/models.py
  src/backers/tests/test_views.py
  src/backers/urls.py
  src/backers/views.py
  src/core/urls.py
  src/home/views.py
  src/locales/fr/LC_MESSAGES/django.po
  src/static/css/_custom.scss
  src/static/js/carousel.js
  src/templates/backers/detail.html
  src/templates/home/home.html
Labels: fonctionnalité
